### ISSUE TITLE
Blank map, doesn't work iOS 9.3.2

### ISSUE THREAD

**Issue by chrismarch** [SilphRoad/reports#11]
iOS 9.3.2, iPhone 6S, Safari and Chrome. Testing in fast WiFi. Refreshing doesn't help. There is no zoom UI. Pinch zoom out doesn't work. "Fire a raid beacon" seems to do nothing. Map area is white.

**Comment by chrismarch** [comment]
This is for https://thesilphroad.com/radio

**Comment by ghost** [comment]
Also reproduced on iOS 9.3.5. The following errors are displayed in Safari debug
![screen](https://user-images.githubusercontent.com/1202164/27821663-be1caf76-60ab-11e7-9758-f6bb6c92fb2b.png)

**Comment by marcoceppi** [comment]
Can you try again after clearing cache?

**Comment by ghost** [comment]
Don't know about OP, but for me - no dice, still see the same issue.

**Comment by marcoceppi** [comment]
Thanks for the feedback, we've rolled out a potential fix for this, could you try again?

**Comment by ghost** [comment]
I can see the map now - both in Safari and Chrome. Thanks!
