### ISSUE TITLE
Private beacons, so spoofers aren't invited

### ISSUE THREAD

**Issue by chrismarch** [SilphRoad/reports#12]
Once you talk to people who show up for a raid, staying in contact isn't hard. What we don't want is to invite spoofers to our coordinated raids. Until there are beacons that only show up for those that have a link to them, or private groups that are invite only to share beacons, I will recommend against this for my group.

**Comment by dronpes** [comment]
Thanks for sharing your thoughts.  The idea of making Raid Beacons _private_ is largely counter to the core idea of the Silph Radio - letting folks who _aren't_ already in your group find you and join your group.

Spoofers will certainly be able to take advantage of the Radio, however - it's true.

The best approach is likely to simply use a private Raid lobby once your group meets up.  By sharing a private password, you lock out spoofers from your Raid group and they don't get to take advantage of your meetup.

**Comment by chrismarch** [comment]
Good idea!
