### ISSUE TITLE
Add more time for "I will be there in x minutes"

### ISSUE THREAD

**Issue by MrGaryTaco** [SilphRoad/reports#17]
## I'm submitting a ...
  - [ ] bug report
  - [x] feature request
##
![screen shot 2017-07-05 at 4 35 42 pm](https://user-images.githubusercontent.com/29933344/27889279-1bd13912-61a0-11e7-8246-b7bf9ae004ac.png)

## **What is the expected behavior or new feature?**

Currently when I fire a raid beacon the maximum number of minutes I can select is 60 minutes.  I would like to have the option of selecting up to 90 minutes.

## **What is the motivation / use case for changing the behavior?**

I usually know I am going to go to a raid as soon as the egg appears on the gym which is usually about 90 minutes.

## **Please tell us about your environment, for bugs:**

- Operating System:  Mobile:iPhone 6s iOS version 10.3.2 and MacMini macOS version 10.12.5
- Browser:   iPhone 6s version 10.3.2 Safari and MacOS Safari version 10.1.1

**Comment by fortepc** [comment]
This one is done!
