### ISSUE TITLE
The map for setting the notification radius doesn't show up

### ISSUE THREAD

**Issue by daveundis** [SilphRoad/reports#2]
I'm submitting a bug report.

On the page for setting your raid beacon radius, the map doesn't show up. A screenshot is attached.

I am using Windows 10 Home 64-bit on a Dell desktop computer.

I am using the Google Chrome browser Version 59.0.3071.115 (Official Build) (64-bit) . I have the following extensions enabled:
Adobe Acrobat
Application Launcher for Drive (by Google)
Earth View from Google Earth
Email this page (by Google)
Google Docs Offline
Google Keep - notes and lists
Google Keep Chrome Extension
Google Play Music
Google Sheets
Google Slides
McAfee WebAdvisor
Pocket
Reddit Enhancement Suite
Save to Pocket
Wikibuy

![clipboard01](https://user-images.githubusercontent.com/29825513/27766116-125a7a8c-5e8b-11e7-85b1-ffdd0ec5c7b0.jpg)

**Comment by dronpes** [comment]
Looks like you simply need to zoom out!
