### ISSUE TITLE
Catalog Capture Rates Missing

### ISSUE THREAD

**Issue by adrazich** [SilphRoad/reports#26]
## I'm submitting a ...
  - [x] bug report
  - [ ] feature request

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

On the [catalog](https://thesilphroad.com/catalog) some of the capture rates are missing for legendaries. Others are there. Raikou, Entei, Suicune, Lugia, Articuno, Zapdos and Moltres all have their capture rate set to 0. Mewtwo on the other hand has it's base capture rate set to 0.06.

### Example
![screen shot 2017-09-14 at 3 46 46 pm](https://user-images.githubusercontent.com/1614075/30452534-fed968d8-9963-11e7-83d8-f8b5909c34fb.png)

## **What is the expected behavior or new feature?**

All Pokemon should have the same base capture rate as listed in the game master file.

## **What is the motivation / use case for changing the behavior?**

Data is wrong.

## **Please tell us about your environment, for bugs:**

- Operating System: OSX - 10.11.6
- Browser: Chrome: 61.0.3163.79
- User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36

## **Other information**
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context)

**Comment by marcoceppi** [comment]
Thanks for pointing this out! We'll work to update this information
