### ISSUE TITLE
Doubled raid tier levels in selection pulldown

### ISSUE THREAD

**Issue by djsteveH** [SilphRoad/reports#4]
![img_3112](https://user-images.githubusercontent.com/29831100/27767787-43fa5a22-5ed0-11e7-82f1-14014e452390.PNG)

iOS 10.3.2, iPhone 6s Plus

I have created several test beacons without issue, but on one occasion the pulldown for the raid level showed double the correct numbers (see attachment). Unknown what the reproduction steps are.

**Comment by dronpes** [comment]
Thanks for the report.  We pushed a potential fix for this last night (EST) - do you remember what time yesterday this screenshot was taken?

**Comment by djsteveH** [comment]
The screenshot shows 12:52am early Sun morning 7/2, and that is EDT.
