### ISSUE TITLE
Beacon does not appear on map until panned

### ISSUE THREAD

**Issue by djsteveH** [SilphRoad/reports#5]
Safari (iPhone and Mac)

After firing a beacon, nothing is displayed on the map until the user pans or otherwise manipulates the controls. Until the user does this it appears that the beacon was not added.

**Comment by marcoceppi** [comment]
This is a known issue that we've attempted to patch in the past - a new update was released about 10 mins ago to address this a bit more. Let me know if you continue to see this.

**Comment by fortepc** [comment]
This seems to be fixed, probably should be makes as finished :-P
