### ISSUE TITLE
raid beacon specific chat

### ISSUE THREAD

**Issue by al1ra1n** [SilphRoad/reports#7]
Your issue may already be reported! Please search on the [issue tracker](../) before creating one.  

**Note: for support questions, please use [/r/TheSilphRoad](https://reddit.com/r/thesilphroad)**. This repository's issues are reserved for feature requests and bug reports.

## I'm submitting a ...
  - [ ] bug report
  - [x] feature request

not sure how much work this would be (probably a lot) but thought id suggest it anyway. how about a raid specific chat. 

once a person implements a raid beacon on the map a chat box is opened for that specific raid/beacon. then when someone else clicks the beacon saying they will attend the raid they are automatically added to that raid chat. then once the raid is over after say a 10min cool down the chat closes.

**Comment by marcoceppi** [comment]
This is something on our roadmap now, thanks

**Comment by malkybck** [comment]
Hi al1ra1n. Our pokemon community couldnt help but notice you join our 5 gyms yesterday, we have a very active raiding community but a lot work difficult hours so some days we end up being just 1 short to conplete raids. Would be great to see you at raids. We have a discord server and a facebook page if youd like to join them to see when we are organising raids. Thanks!!!

**Comment by marcoceppi** [comment]
This feature has been added.
