### ISSUE TITLE
please let me launch a beacon at the gym location before I leave home

### ISSUE THREAD

**Issue by NibblesMcGiblet** [SilphRoad/reports#8]
FEATURE REQUEST:
This request is about firing location for beacons. Firstly, I would love to be able to just click a button to make the map find my current location so that if I'm AT a gym I can just click to auto locate me, then click to fire.

Secondly, I'm very rural and have to drive between 10-30 minutes to join my fb group for raids. I would like to be able to put up a beacon from home to indicate I will be at a raid 30 minutes away so that I can see how many others will also commit to it before I drive all that way. However,at this time I can't find any way to search by gym name/description or even street address or city to find the right place to fire the beacon, or any way to tell people WHICH gym I will be at in high density areas when choosing to fire a beacon. 

Likewise, clicking an existing beacon doesn't tell me the gym name or location, which I expected it to do (example: "Holy Cross Church, Main street, Anytown, NY" coming up when I click a beacon would tell me what I need to know). 

In relation to this, I can see city names on the map but nothing more specific comes up and I only sort of recognize the shapes of the roads enough to locate one major highway through my greater metropolitan area, so I'm hopeful that this is going to eventually be a more detailed map than the nest atlas, which is ok for finding rough locations but gyms are VERY specific addresses so will require a more detailed map view IMO. If I fire off a beacon at this time I can only get it specific enough for people to know that I will be at a raid somewhere in a particular city. I'd like to be able to have it gym-specific (and thought that's what this was meant to be). 

Thanks for everything! Looking forward to making this an app I keep open at all times with pogo once it's not browser based (since having a browser AND pogo open crashes the game right now).

**Comment by NibblesMcGiblet** [comment]
![example](https://user-images.githubusercontent.com/29834452/27769343-83df1a0e-5ef5-11e7-9b68-206c8604744c.png)

Here is an example of what the map looks like for me. I cannot find a specific address in order to place a beacon on a gym this way, nor can I use it to drive directly to a gym based on a beacon's map location. Please make it so that I can either enter an exact address into a search bar to be brought to the right place to drop a beacon/see if anyone has fired a beacon for that specific gym yet. Or alternatively if it was a satellite view that zooms nearly to street level I could probably make out which buildings are which and could find the r ight place to set off a beacon that way. 

edit- I clicked on the bullseye looking button (there are no tool tips popping up so I don't know what they do or are called) and it seemed to attempt to auto-locate me. This resulted in a nearer zoom level which showed some street names, but it was so zoomed in as to be disorienting. When I zoomed out enough to see where it was placing me, the street names disappeared as did all streets aside from highways. If at all possible, please make it so we can zoom a level or two more before everything disappears - it's very difficult to get my bearings this way.

Edit 2 - as I am typing the reports, things are still changing. I can now see some streets and some street names at a more workable zoom level. This is great, I hope that it will continue to refine and improve so that I can eventually differentiate between setting a beacon at one gym, or another, when they're in nearly intersecting radiuses. At this time I'm not sure I could do that, but I can already see the ability in the near future. thanks again!

**Comment by marcoceppi** [comment]
You've got a bunch of features and bugs in this issue.

> Firstly, I would love to be able to just click a button to make the map find my current location so that if I'm AT a gym I can just click to auto locate me, then click to fire.

That's the second button from the top in your screen shot.

> I can't see streets

Try clearing your cache as a change went out earlier today to help address this. You will also need to zoom in, using the navigation buttons on the left to see more street names.

We're still tweaking what shows up where, here it's a disadvantage, but in metropolitan area maps with street names take up the entire screen.

> Let me type an address

We're looking at ways to make this a better experience, thanks for the report
